sudo: required

services:
  - docker

language: python


script:
  - python -m pytest -v
  - source cicd-buzz/venv/bin/activate
  - bandit -r cicd-buzz/buzz/generator.py
  
after_success:
  - sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
