sudo: required

services:
  - docker

language: python

install:
  - pip install -r requirements.txt
  - sudo apt-get install rpm
 

script:
  - python -m pytest -v
  - bandit -r ./*.py -f html -o bandit-result || true
  - git add bandit-result
  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.3.2-release.zip 
  - unzip download_file?file_path=dependency-check-5.3.2-release.zip
  - ls -a
  - sh dependency-check/bin/dependency-check.sh --project TEST--scan ./ --out ./dependecy-result
  - git add dependecy-result
  - wget https://github.com/aquasecurity/trivy/releases/download/v0.8.0/trivy_0.8.0_Linux-64bit.deb
  - sudo dpkg -i trivy_0.8.0_Linux-64bit.deb
  - trivy image -f json -o trivy-result.json almaz045/eed81acfef2d:latest
  - ls -a
  - git add trivy-result
  - git commit -m "results"
  - git push origin master

  
after_success:   
  — sh .travis/deploy_dockerhub.sh 
 

deploy:
  provider: heroku
  app: almazvakh
  api_key:
    secure: iqo2ro2rCYtCTOiCxOHUol9HEoKKMP6HQZnm2vX1oeLDSrVkKLbsFoxF0aY5L8AwPRj0aXjXppmyjj87bnz2baBtxbIxarnfUO11E62TpTPDAmB3PU9V3nZOksllS91gEVIAAGrAP8jkvV0gXBwhTVxF6rMsv3LlZ5h2M+W4Ua/mBrHF+cBVgiZhtFwYMaYKn6Tp8SLa3JDK5EJ4rwoJJVmqccRrhv7CmUY5AKj2WYpIapBn2B02/zWsSrHoMmpIaHqnS69sQMufHhPOvXNemrvgyWT2p1NELrfQdvkMlSERHo7sja+rdApieae1Dju5q/URvEUVsRYip6h2PeZba9xa7vVnwbf9K/htssDw0uS8NbQcRZhjrRdjmd5fuIcRFyHPzxn89f13eB4Fw70cBXjclVmXMzvS+znMqAw6Mw3XB1leSdFIVXjDg9zrMsdpqzg47Mifa73SSqU38VHY/HpoMVkxaZGXxjfRMcS0Th84XUn0jBbOZUT6UdiboPgExNulKtbRkyogHHGPKzQQsoIv8Y+u1zt8HlM2DVqxRDlFjlEC7cHS/5bLjHajuFAjrlPgsI5VekC4W25nUEEgbVa9tVVhHIo0m9voYzpgWmAgIHUhuQf6GkVxaf9/nen8VDDfW5/PXOfLgbyssvqW52qWx6FoREdPu00RphUvAfc=
  skip_cleanup: true

after_deploy:
  - docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained     --start-options '-config api.disablekey=true' http://almazvakh.herokuapp.com -l Medium -l Low
  
  
  
  
  
  


