sudo: required

services:
  - docker

language: python

script:
  - python3.7.1 -m pytest -v

after_success:
  — sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

deploy:  
  provider: heroku
  app: almazvakh
  api_key:     
    secure: pO86yrBt0UI9sUsNTvP+azRwwmQM9qQRNaie4CMbFmHlm4AlyD/iNS5VKao2D4ryZb15rx/tIxZloBEv4pxAZ3EwVk7mrxJwMCbKW6EYkmny97s/Afd9/4BFBO7yp5rEJeAVcPuXAOSPZBlpPvmHMh9xU4s9+QcokI/31lqJkvf4mj3F5twFPwE2plf3zTACd3O0ERQrn4+EdfQ6V/y1sptfIpAYhtkIMPxh0z0ylyrDPZRjd/4wBbtrYAFi03KxeaICV32fe2WTUucm6yIjwgifLTM5hdjQtUgiJEuP2ngAvnNhYR9NBa+Ox6jIUVCGg5mdmMZ6HscOUQ60GYUtai9medyPr8jcQZ7Pj5CnMIvKhu2YXctdeeJdCgvGEg/o5BgdILIjHe3F4mGXCYn7s8Goe7+DUaRd2fuxzLSjnUlGW7l2e0pXs5Gg4ff3nvnAsmIRZW+mtwLRWqeGL1H56efXm/stP3l32bTGyf32jgoBSwIKjgApjilzPzX/EEfMIa2APynUJu8SX7eUCuSEcM7Bt112Deh1HSrXogjOPtrB3WvtWySbtijdjTL7KZYYuj48AH3kUmeBAsm5qQy+unXRCNCaAaGNw65MIJ8QCBKfA4bWYeEPVDyCgWUccIibMkD+VnDBFb5mBYU3iyWEzi+Cycr8gWO2D81leChifv0=
  skip_cleanup: true
 
