sudo: required

services:
  - docker

language: python

install:
  - pip install -r requirements.txt
  - sudo apt-get install rpm
 

script:
  - python -m pytest -v
  - mkdir results
  - bandit -r ./*.py -f html -o results/bandit-result || true
  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.3.2-release.zip 
  - unzip download_file?file_path=dependency-check-5.3.2-release.zip
  - sh dependency-check/bin/dependency-check.sh --project TEST --scan ./ --out ./results/dependecy-result
  - wget https://github.com/aquasecurity/trivy/releases/download/v0.8.0/trivy_0.8.0_Linux-64bit.deb
  - sudo dpkg -i trivy_0.8.0_Linux-64bit.deb
  - trivy image -f json -o results/trivy-result.json almaz045/eed81acfef2d:latest
  
after_success :   
  
  — sh .travis/deploy_dockerhub.sh  

deploy:
  provider: releases
  user: almaz045
  password: QEPwpyw30ZDvdN1tGyd6RUSIfWXGka8RaP19zlHeot9/3jZ3nkuv3i2VIY8h15TS3J1wIdn/eYAr/skCRy7xU1wyesL0bZGgLVg9+fTqLo8KCwRzC5LksSCxUuhvlDxDRXzZ5e5unsQdccWgxVFhBCOCEukwJ0c0afFJ5Qy8COXiNr90V3En0wx24N9ZKhP6LndbebJUV3ZAg6o2yoYqyXSJ8zWl+j3q36GvjaK1rb298f4n17Wno1F9NX45Nv3OAA/ePi/21HS9rXNvtRSIKpmWNLuMGiABMwWrvrfPLmChPIB5PUIlv+GZPILy1PfUxMSbZ0Qy9c2lruU+MAcADtpSWVqblYj/jkN9g7MXDxAvxIML9Ev0tzUSIuZGiuKCzyD6S+pxTtXgp2WPBt/W8E/XUVSDBIwtHBQ6jLb2Xdg2ShCXo5KlgY+3UArpUwL3s1s/rn6RbmAoQlXBNId/SnYWplOMtB24+Lu9fYugAkDc7EL1Ks+a2xPcXJUxWFhbIqMhkxmm5qlgbT77/aANxJTITJsao/LALrSHsZKAN6ju8BtVFcOM85lXKECvGqstXA4f1DPLQz8kaVZXXg58EVz5VjXSowcmR/Qo3CtwXd5zbVHHrWmYgqHvAXh4uYpyGgTyb0Vg5t3h0wvsNhzxgvNOYWDbespZugH8/kw00Ig=
  file: results 
  skip_cleanup: true
  on:
    tags: false
  provider: heroku
  app: almazvakh
  api_key:
    secure: iqo2ro2rCYtCTOiCxOHUol9HEoKKMP6HQZnm2vX1oeLDSrVkKLbsFoxF0aY5L8AwPRj0aXjXppmyjj87bnz2baBtxbIxarnfUO11E62TpTPDAmB3PU9V3nZOksllS91gEVIAAGrAP8jkvV0gXBwhTVxF6rMsv3LlZ5h2M+W4Ua/mBrHF+cBVgiZhtFwYMaYKn6Tp8SLa3JDK5EJ4rwoJJVmqccRrhv7CmUY5AKj2WYpIapBn2B02/zWsSrHoMmpIaHqnS69sQMufHhPOvXNemrvgyWT2p1NELrfQdvkMlSERHo7sja+rdApieae1Dju5q/URvEUVsRYip6h2PeZba9xa7vVnwbf9K/htssDw0uS8NbQcRZhjrRdjmd5fuIcRFyHPzxn89f13eB4Fw70cBXjclVmXMzvS+znMqAw6Mw3XB1leSdFIVXjDg9zrMsdpqzg47Mifa73SSqU38VHY/HpoMVkxaZGXxjfRMcS0Th84XUn0jBbOZUT6UdiboPgExNulKtbRkyogHHGPKzQQsoIv8Y+u1zt8HlM2DVqxRDlFjlEC7cHS/5bLjHajuFAjrlPgsI5VekC4W25nUEEgbVa9tVVhHIo0m9voYzpgWmAgIHUhuQf6GkVxaf9/nen8VDDfW5/PXOfLgbyssvqW52qWx6FoREdPu00RphUvAfc=
  skip_cleanup: true

after_deploy:
  - docker run -i owasp/zap2docker-stable zap-cli quick-scan --self-contained     --start-options '-config api.disablekey=true' http://almazvakh.herokuapp.com -l Medium -l Low
  
  
  
  
  
  


