sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  — sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

deploy:  
  provider: heroku
  api_key:
    secure: 63cad9b7-9890-42e5-af1c-8778852435b7
  skip_cleanup: true
 
