sudo: required

services:
  - docker

language: python

env: venv

script:
  - python -m pytest -v
  - bandit
after_success:
  - sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
