sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v
  - bandit python3-bandit -r /cicd-buzz/buzz/generator.py -f html -o outputfile
after_success:
  - sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
