sudo: required

services:
  - docker

language: python


script:
  - python -m pytest -v
  - ./bandit-travis/scan.sh

install: 
  - ./bandit-travis/install.sh
  
  
  
after_success:
  - sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh
