sudo: required

services:
  - docker

language: python

#before_install: 
 # - git clone https://github.com/TravisToolbox/bandit-travis.git

#install: 
#  - ./bandit-travis/install.sh

script:
  - python -m pytest -v
 # - ./bandit-travis/scan.sh
  
after_success:
  - sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

deploy:
provider: heroku
api_key:
secure: 2e30c7fc-4902-4a18-9114-28cf820f2299
