sudo: required

services:
  - docker

language: python

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -v
  - bandit —exit-zero -r ./*.py
after_success:   
  — sh .travis/deploy_dockerhub.sh 
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh

deploy:
  provider: heroku
  app: almazvakh
  api_key:
    secure: iqo2ro2rCYtCTOiCxOHUol9HEoKKMP6HQZnm2vX1oeLDSrVkKLbsFoxF0aY5L8AwPRj0aXjXppmyjj87bnz2baBtxbIxarnfUO11E62TpTPDAmB3PU9V3nZOksllS91gEVIAAGrAP8jkvV0gXBwhTVxF6rMsv3LlZ5h2M+W4Ua/mBrHF+cBVgiZhtFwYMaYKn6Tp8SLa3JDK5EJ4rwoJJVmqccRrhv7CmUY5AKj2WYpIapBn2B02/zWsSrHoMmpIaHqnS69sQMufHhPOvXNemrvgyWT2p1NELrfQdvkMlSERHo7sja+rdApieae1Dju5q/URvEUVsRYip6h2PeZba9xa7vVnwbf9K/htssDw0uS8NbQcRZhjrRdjmd5fuIcRFyHPzxn89f13eB4Fw70cBXjclVmXMzvS+znMqAw6Mw3XB1leSdFIVXjDg9zrMsdpqzg47Mifa73SSqU38VHY/HpoMVkxaZGXxjfRMcS0Th84XUn0jBbOZUT6UdiboPgExNulKtbRkyogHHGPKzQQsoIv8Y+u1zt8HlM2DVqxRDlFjlEC7cHS/5bLjHajuFAjrlPgsI5VekC4W25nUEEgbVa9tVVhHIo0m9voYzpgWmAgIHUhuQf6GkVxaf9/nen8VDDfW5/PXOfLgbyssvqW52qWx6FoREdPu00RphUvAfc=
  skip_cleanup: true
